### ISSUE TITLE
conf setting

### ISSUE THREAD

**Issue by madmicio** [MarcBoettinger/Adafruit_Fingerprint_Sensor_Library#2]
![image](https://user-images.githubusercontent.com/42836292/98450315-2bb57a00-213c-11eb-9827-25054a3bdac8.png)
C:\Users\mauri\OneDrive\Documents\Arduino\finger test\finger_test\finger_test.ino:48:16: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
 char* mqttio = "12345"; // Broker PI Wert
                ^
C:\Users\mauri\OneDrive\Documents\Arduino\finger test\finger_test\finger_test.ino:49:20: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
 char* confidence = "67890"; // Broker PI Wert

what is this?
char* mqttio = "12345"; // Broker PI Wert
char* confidence = "67890"; // Broker PI Wert

**Comment by MarcBoettinger** [comment]
Please read the detailed description on the Wordpress blog.
